#! /bin/sh
# /etc/init.d/funprinter
#
PIDFILE="/tmp/funprinter.pid"
# Carry out specific functions when asked to by the system
case "$1" in
  start)

    if [ -f $PIDFILE ]; then
	echo "there's already a PIDFILE so do not start another proces"    
else
    PID=`sudo /usr/bin/ruby /home/pi/funprinter/printer.rb > /dev/null 2>&1 & echo $!`
      echo $PID
      if [ -z $PID ]; then
          printf "%s\n" "Fail"
      else
          echo $PID > $PIDFILE
          printf "%s\n" "Ok"
      fi
      echo "Starting funprinter"
    fi 
 ;;
 status)
	printf "%-50s" "Checking $NAME..."
	if [ -f $PIDFILE ]; then
	    PID=`cat $PIDFILE`
	    if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
	        printf "%s\n" "Process dead but pidfile exists"
	    else
	        echo "Running"
	    fi
	else
	    printf "%s\n" "Service not running"
	fi
;;
  stop)
    echo "Stop funprinter"
    printf "%-50s" "Stopping $NAME"
    PID=`cat $PIDFILE`
    if [ -f $PIDFILE ]; then
        sudo kill $PID
        printf "%s\n" "Ok"
        sudo rm -f $PIDFILE
    else
        printf "%s\n" "pidfile not found"
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/funprinter {start|stop}"
    exit 1
    ;;
esac

exit 0
